// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Solutions
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        int sumS = 0, sumT = 0;

        // Calculate the sum of ASCII values of characters in string s.
        for (int i = 0; i < s.length(); i++)
        {
            sumS += s[i];
        }

        // Calculate the sum of ASCII values of characters in string t.
        for (int i = 0; i < t.length(); i++)
        {
            sumT += t[i];
        }

        // Calculate the difference in the sums of ASCII values to find the differing character.
        return static_cast<char>(sumT - sumS);
    }
};
